### ISSUE TITLE
Qestion: PE File certificate

### ISSUE THREAD

**Issue by saeschdivara** [wisk/medusa#25]
Hi,
How can I find out where the section lies in which the certificate is stored?
I found IMAGE_DIRECTORY_ENTRY_CERTIFICATE which didn't help me much: https://github.com/libvmi/libvmi/blob/master/libvmi/peparse.h

**Comment by wisk** [comment]
Hello,

I'm going to assume to want to access this information from medusa.
The real define is `IMAGE_DIRECTORY_ENTRY_SECURITY` and this feature is called **Authenticode** for further information, take a look at this [link](http://www.microsoft.com/whdc/winlogo/drvsign/Authenticode_PE.mspx)

It might be a little bit tricky to retrieve it since it should not be mapped on memory, and unmapped data are discarded by the PE loader (_ldr_pe_), so if you wanna retrieve this field, get the badly named RVA value from the **data directories[PE_DIRECTORY_ENTRY_SECURITY]** (in pe.hpp `IMAGE_` is replaced with `PE_` to avoid conflict) and its size to read it using the **BinaryStream**.

**Comment by saeschdivara** [comment]
Ok, thanks
I will try to do that and will give you feedback as soon as I've tried it

**Comment by wisk** [comment]
Hi,

Since this feature is not really useful for a disassembler and there's no news since 2015, I close the issue.
Feel free to re-open it if needed.

Thanks.
